name: monorepo

packages:
  - .
  - packages/**

scripts:
  localize:
    description: Generate Localization for all modules
    run: flutter gen-l10n
    exec:
      concurrency: 1
  analyze:
    run: melos exec -- "flutter analyze"
    description: Run `flutter analyze` in all packages

  format:
    run: melos exec -- "dart format . --set-exit-if-changed"
    description: Run `flutter format .` in all packages

  generate:
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for Flutter packages in this project.

  clean:
    run: melos exec -c 1 -- "flutter clean"
    description: Run `flutter clean` in all packages
  upgrade:
    run: melos exec -c 1 -- "flutter upgrade"
    description: Run `flutter upgrade` in all packages

  cache-repair:
    run: melos exec -c 1 -- "flutter pub cache repair"
    description: Run `flutter pub cache repair` in all packages
