arb-dir: lib/src/l10n/arb
template-arb-file: settings_en.arb
output-dir: lib/src/l10n/gen
output-class: SettingsLocalizations
output-localization-file: settings_localizations.dart
synthetic-package: false # set this as false to import the delegate in the main project
nullable-getter: false