arb-dir: lib/src/l10n/arb
template-arb-file: common_en.arb
output-dir: lib/src/l10n/gen
output-class: CommonLocalizations
output-localization-file: common_localizations.dart
synthetic-package: false # set this as false to import the delegate in the main project
nullable-getter: false