arb-dir: lib/src/l10n/arb
template-arb-file: subscription_en.arb
output-dir: lib/src/l10n/gen
output-class: SubscriptionLocalizations
output-localization-file: subscription_localizations.dart
synthetic-package: false # set this as false to import the delegate in the main project
nullable-getter: false