name: subscription
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
resolution: workspace



dev_dependencies:
  flutter_test:
    sdk: flutter
  responsive_builder: ^0.4.2
  build_runner: ^2.3.3
  injectable_generator: ^2.6.2
  auto_route_generator: ^8.0.0
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.0

