arb-dir: lib/src/l10n/arb
template-arb-file: funds_en.arb
output-dir: lib/src/l10n/gen
output-class: FundsLocalizations
output-localization-file: funds_localizations.dart
synthetic-package: false # set this as false to import the delegate in the main project
nullable-getter: false